### ISSUE TITLE
No access to docker.sdelements.com

### ISSUE THREAD

**Issue by oaeide** [SecurityCompass/moodle-docker#29]
Hi. I have been trying to use your repository to set up a moodle container.

Using 

docker-compose --file docker-compose.yml up --force-recreate --no-deps --detach

I get

Pulling nginx-php-moodle (docker.sdelements.com:443/moodle/nginx-php-moodle:7.2-3.5.1)...
ERROR: Get https://docker.sdelements.com:443/v2/moodle/nginx-php-moodle/manifests/7.2-3.5.1: no basic auth credentials

If the repo is meant to be private, I do apologize. I would suggest stating that in the repo description.

**Comment by hrpatel** [comment]
@oaeide 
Apologies for the late reply, I completely missed this note. 

- Do you still use this container? If so, I can try to find some time to publish a version on Docker hub
- Where do you suggest putting the note? I don't see any existing reference to our docker registry except in the CI configuration

**Comment by oaeide** [comment]
Hey! No problem. I'm using the one from bitnami or moodle directly I think, so no need to stress about it :)

**Comment by hrpatel** [comment]
Thanks for the update! 
I'll close this for now.
